name: Deploy Full Stack (MVP - External Redis)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    
  deploy-frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-frontend.yml
    needs: deploy-backend
    secrets: inherit
    
  notify:
    name: Deployment Notification
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    
    steps:
      - name: Deployment status
        run: |
          echo "⭐⭐⭐ DEPLOYMENT COMPLETE ⭐⭐⭐"
          echo "Date: $(date)"
          echo ""
          echo "Frontend URL: https://${{ secrets.CLOUDFRONT_DOMAIN_NAME || secrets.S3_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com/"
          echo "Backend URL: http://${{ secrets.EB_ENVIRONMENT_NAME }}.${{ secrets.AWS_REGION }}.elasticbeanstalk.com/"
          echo ""
          echo "Using external Redis service"
